package org.producteev.model

class Task(
  val id_task: Integer,
  val id_dashboard: Integer,
  val id_creator: Integer,
  val id_responsible: Integer,
  val assign_by: Integer,
  val time_created: String,
  val title: String,
  val status: Integer,
  val star: Integer,
  val vote: Integer,
  val deadline: String,
  val all_day: Integer,
  val reminder: Integer,
  val repeating_interval: Integer,
  val repeating_value: Integer,
  val hot: Integer,
  val progression: Integer,
  val public: Integer,
  val uid_lastchange: Integer,
  val time_lastchange: String,
  val from: Integer,
  val time_status: String,
  val r: Integer,
  val w: Integer,
  val x: Integer,
  val d: Integer,
  val viewed: Integer,
  val deleted: Integer,
  val nb_note: Integer,
  val nb_new_note: Integer
)
